### ISSUE TITLE
Device parameters in ECD control

### ISSUE THREAD

**Issue by EeshGupta** [alec-eickbusch/ECD_control#1]
In the Fock_prep_ECD example python notebook, I couldn't find any place where device parameters were specified. Shouldn't we have to specify the qubit and cavity frequencies, chi, and other constants to find gates (like in GRAPE)?

**Comment by EeshGupta** [comment]
From the paper (first 3 pages), is the reason we can ignore device parameters because we are assuming that the experimentalist already has displacement for cavity, pauli gates for qubits at hand. And our role is, given these gates,  for what parameters beta phi theta can we use those gates to prepare some target state.

**Comment by alec-eickbusch** [comment]
Hi Eesh, 

Yes, you are correct. Essentially, the optimization is a two-step process. First, the ECD parameters (betas, phis, thetas) are found for a given control problem. This first step is independent of device-specific parameters.

Once the ECD parameters are found, the experimentalist supplies device-specific parameters such as chi and amplitude calibrations. These are used along with the ECD parameters to compile a pulse that can be directly played in experiment.

I've updated the Fock_prep_ECD example [here](https://github.com/alec-eickbusch/ECD_control/blob/2b80d5b4b144fcd2f546fc6ff404ae6fb0d5ff50/examples/Fock_prep_ECD_opt.ipynb) to include this second pulse-compilation step, including comments that specify the meaning of the various calibration parameters.


#
