### ISSUE TITLE
Sign error in Phase space trajectory in ECD_pulse_construction.py file

### ISSUE THREAD

**Issue by EeshGupta** [alec-eickbusch/ECD_control#3]
Hi Alec, 
in lines 163, 210, 249 and 260 of ECD_pulse_construction.py, the cavity kerr term has a negative sign in front. But in S5 of the paper, the cavity kerr has + sign in both equations. Is this a bug or am I missing something?

**Comment by EeshGupta** [comment]
A similar issue happens in line 263 of the same file where the coefficient in front is -i but in the paper (second equation of S5), that term has the coefficient +i

**Comment by alec-eickbusch** [comment]
Hi Eesh,
Thank you for pointing this out. Indeed, we used a different sign convention internally (and in the ECD code in this repo) than what is in the paper. I will update the code and examples to match the sign convention used in the paper.

**Comment by alec-eickbusch** [comment]
Updated sign conventions to match ECD paper in  1aada654f06d18bb593b82cc018607e3c5892e1e
